version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: basic_postgres_db
    environment:
      POSTGRES_DB: basic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1100
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data